### ISSUE TITLE
Request fixed at 2.28.1 causes conflicts with other packages

### ISSUE THREAD

**Issue by dtroelofsprins** [EUDAT-B2HANDLE/PYHANDLE#113]
Dear pyhandle developers, 

I'm having issues with other packages that require higher versions of the request package f.e. requests>=2.31.0. Whereas pyhandle requests is fixed at 2.28.1

Is it possible to set this a bit less tight / not lock on a specific version?

=> also included in this [PR](https://github.com/EUDAT-B2HANDLE/PYHANDLE/pull/111) created by @aquatix

**Comment by themiszamani** [comment]
New release of pyhandle is available .  Please have a look at it.

**Comment by dtroelofsprins** [comment]
I've checked the latest version (1.3.1) and the conflicts with my other packages are resolved now.

THANKS!
