### ISSUE TITLE
Cannot load credentials (key, certificate) from subdirectory

### ISSUE THREAD

**Issue by merretbuurman** [EUDAT-B2HANDLE/PYHANDLE#34]
When I run a script using pyhandle that loads the credentials info from a JSON file that sits in a subdirectory, where also private key and certificate are sitting, I cannot load them using relative paths.

Files:
```
workingdir/
workingdir/script.py
workingdir/credentials/
workingdir/credentials/creds.json
workingdir/credentials/privkey.pem
workingdir/credentials/clientcert.pem
```
Contents of the `creds.json`:

```
{
    "private_key": "./privkey.pem",
    "certificate_only": "./clientcert.pem",
    "prefix": "21.xxx",
    "handleowner": "200:0.NA/21.xxx",
    "HTTPS_verify": "./xxx_bundle.crt",
    "client": "rest",
    "handle_server_url": "xxx"
}
# Paths of key+cert are relative to JSON file!
```

And I want to do this:

```
creds = pyhandle.clientcredentials.PIDClientCredentials.load_from_JSON('./credentials/creds.json')
client = pyhandle.handleclient.PyHandleClient('rest').instantiate_with_credentials(creds, HTTPS_verify=False)
```

But I get an error:

```
pyhandle.handleexceptions.CredentialsFormatError: Problem with credentials: The certificate file was not found at the specified path: ./clientcert.pemThe private key file was not found at the specified path: ./privkey.pem.
```

If I add the subdirectory to the JSON file:

```
{
    "private_key": "./credentials/privkey.pem",
    "certificate_only": "./credentials/clientcert.pem",
    "prefix": "21.xxx",
    "handleowner": "200:0.NA/21.xxx",
    "HTTPS_verify": "./xxx_bundle.crt",
    "client": "rest",
    "handle_server_url": "xxx"
}
# Paths of key+cert are relative to script!
```

Then I also get an error:

```
pyhandle.handleexceptions.CredentialsFormatError: Problem with credentials: (certficate file): The file was not found at the specified path: /workingdir/credentials/credentials/clientcert.pem.
```

Now the subdirectory is added twice!
No way out!

**Comment by merretbuurman** [comment]
Problem is here: 

The function `get_absolute_path` in `pyhandle/util/pathutils.py` does find and return the correct path (https://github.com/EUDAT-B2SAFE/PYHANDLE/blob/1f3e075c5eef40f78970a0d3d57a933a1baf1818/pyhandle/util/pathutils.py#L3), and it is also then stored in the right attribute in `__check_file_existence` in `pyhandle/clientcredentials.py` (https://github.com/EUDAT-B2SAFE/PYHANDLE/blob/1f3e075c5eef40f78970a0d3d57a933a1baf1818/pyhandle/clientcredentials.py#L264).

But `instantiate_with_credentials`  (https://github.com/EUDAT-B2SAFE/PYHANDLE/blob/1f3e075c5eef40f78970a0d3d57a933a1baf1818/pyhandle/client/resthandleclient.py#L239) in `pyhandle/client/resthandleclient.py` calls `get_all_args` (https://github.com/EUDAT-B2SAFE/PYHANDLE/blob/1f3e075c5eef40f78970a0d3d57a933a1baf1818/pyhandle/clientcredentials.py#L348) which returns `all_args` which does not contain this correction!

So I guess I must store the corrections there.

**Comment by themiszamani** [comment]
Create a README file to guide users.

**Comment by themiszamani** [comment]
https://github.com/EUDAT-B2HANDLE/PYHANDLE/pull/55 @merretbuurman  please check
