### ISSUE TITLE
REST client: Cannot add options

### ISSUE THREAD

**Issue by merretbuurman** [EUDAT-B2HANDLE/PYHANDLE#38]
Sometimes I need the option `?auth` in GET requests to make sure the primary server is requested. I cannot pass that.

**Comment by merretbuurman** [comment]
I added the `auth` options (and other params accepted by `HTTP GET` to the methods that read handle records.
But if you pass it to the methods that write records, it is taken as one of the key-value-pairs that users want to register, so it will be added to the handle record:

```
URL = www.dkrz.de
VERSION = 23
auth = True
```

That is hardly desired. But if we delete any `auth` passed by the user, then users cannot register that as a key-value pair anymore, even if that's intended. Hm. Any thoughts?

Obviously we could add another parameter, e.g. `force_add` or so... But that might be over the top.

**Comment by merretbuurman** [comment]
(Except for that last comment, the things were done in https://github.com/EUDAT-B2HANDLE/PYHANDLE/pull/65 ).

**Comment by themiszamani** [comment]
We are going to support the auth options in the read handle records.
The documentation informs the users that all the values they pass in the that write records, are taken as  key-value-pairs and will be added to the handle record.

**Comment by merretbuurman** [comment]
I just noticed that "type" can be repeated, so I need to pass it differently than in this PR. Please wait with merging, thanks!

**Comment by themiszamani** [comment]
https://github.com/EUDAT-B2HANDLE/PYHANDLE/pull/65
