### ISSUE TITLE
Return values should be consistent

### ISSUE THREAD

**Issue by merretbuurman** [EUDAT-B2HANDLE/PYHANDLE#40]
* The method `modify_handle_value` (https://github.com/EUDAT-B2HANDLE/PYHANDLE/blob/master/pyhandle/client/resthandleclient.py#L389) does not return anything if successful.
* Same for `delete_handle_value` (https://github.com/EUDAT-B2HANDLE/PYHANDLE/blob/master/pyhandle/client/resthandleclient.py#L502) and `delete_handle`
* **But** `register_handle_json` returns the handle: https://github.com/EUDAT-B2HANDLE/PYHANDLE/blob/master/pyhandle/client/resthandleclient.py#L600 , same for `__handle_registering` and all those wrapping it.

**Comment by themiszamani** [comment]
For  all of the methods above return the handle.
