### ISSUE TITLE
check_handle_syntax fails with unhelpful error message when "hdl:prefix/suffix" is passed

### ISSUE THREAD

**Issue by merretbuurman** [EUDAT-B2HANDLE/PYHANDLE#49]
When I call the method `check_handle_syntax(string)` with the handle `hdl:21.140x/bla` I get this error message:

> pyhandle.handleexceptions.HandleSyntaxError: Handle hdl:21.1410x/bla does not have expected syntax: Index is not an integer.
> Expected: index:prefix/suffix

But  `hdl:21.140x/bla` is a perfectly valid handle. At least, the error message should be more helpful.

Because of the colon `:`, the method assumes we're trying to pass a single field, i.e. with an index in front. That does not make sense to me, as we're checking the syntax of a handle.

Where?

* https://github.com/EUDAT-B2HANDLE/PYHANDLE/blob/1f3e075c5eef40f78970a0d3d57a933a1baf1818/pyhandle/utilhandle.py
* https://github.com/EUDAT-B2HANDLE/PYHANDLE/blob/1f3e075c5eef40f78970a0d3d57a933a1baf1818/pyhandle/utilhandle.py#L66

**Comment by themiszamani** [comment]
We need to support 

- both 21.140x/bla and hdl:21.140x/bla (hdl: only) . 
- update the error message.

**Comment by merretbuurman** [comment]
Fixed this, at least partially, in PR #58 . 

(However, this may backfire, as the handle server REST API does not accept handles with "hdl:" prepended, as far as I know - so scripts who relied on the syntax check to filter those, will run into trouble.)

Also, I strongly argue that handles with an index prepended (as in "301:21.1410x/ADMINLIST" should **not** pass the syntax check, as they are not handle strings, but refer to single fields in a handle record. Checking handle string syntax _with_ a integer index should always be done by the specific method `check_handle_syntax_with_index(...)`.

Who is with me?

**Comment by merretbuurman** [comment]
As Themis agreed, I added commits that implement the stuff from the comment below, and made another PR #63 . If that one passes tests and review, we can close this here.

**Comment by merretbuurman** [comment]
Closing this. Themis just merged the PR #63
