### ISSUE TITLE
python_requires in setup.py not PEP440 compliant

### ISSUE THREAD

**Issue by dtroelofsprins** [EUDAT-B2HANDLE/PYHANDLE#88]
Dear pyhandle developers,

I encounter issues with the Python requirements in the setup.py `python_requires='>=3.6.*<3.11'` when running pipenv install. The requirement is included in the Pipfile.lock, but not correctly and subsequently pyhandle is not installed due to: `Ignoring pyhandle: markers 'python_version >= "3.6.*<3.11"' don't match your environment` whereas I'm using Python 3.10.8.
This requirement turns out to be not PEP440 compliant as it should be according to the [description](https://setuptools.pypa.io/en/latest/references/keywords.html).

I think it should become something like this: `python_requires='>=3.6, <3.11'`

**Comment by themiszamani** [comment]
Thank you for your notice. We will check and update !

**Comment by themiszamani** [comment]
Dear [dtroelofsprins](https://github.com/dtroelofsprins) 

We just uploaded a new version to pypi. Could you please check?

Kind regards

**Comment by aquatix** [comment]
With the current version on pypi, I get this on Python 3.11:

`error in pyhandle setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.6.*<3.11'`

For some reason it works fine on 3.10

**Comment by themiszamani** [comment]
Dear @aquatix 

The answer is correct . It is for python <3.11
Working on new versions  > 3.11

**Comment by aquatix** [comment]
Any news? There's no major changes between the already supported Python 3.10 and the newer 3.11, so I wonder what fixes are needed.

Can we help?

**Comment by dtroelofsprins** [comment]
> Dear [dtroelofsprins](https://github.com/dtroelofsprins)
> 
> We just uploaded a new version to pypi. Could you please check?
> 
> Kind regards

Sorry for my late response, up till now I didn't need to rebuild my Pipfile.lock, so never thought of it again. But with these changes things work fine now! Many thanks!
