### ISSUE TITLE
Uninstallable because hard-dependency on requests==2.23.0

### ISSUE THREAD

**Issue by aquatix** [EUDAT-B2HANDLE/PYHANDLE#93]
Because the pyhandle package locks requests on version 2.23.0 (not higher, not lower), it is uninstallable together with some other packages in our project that demand newer versions of requests.

Is there a reason that setup.py locks it on this version?

**Comment by themiszamani** [comment]
Dear @aquatix 

It is fully tested with this version . Is there a specific version of requests you want to use?

**Comment by aquatix** [comment]
Hey @themiszamani :)

2.23.0 is 3 years old now; we have a few dependencies (packages installed through pip) that demand at least 2.25.0 Our application itself also makes use of the `requests` library, and having it depend on such an old version is not ideal.

Version 2.28.1 is the latest, and that's from June 2022 so already a while ago.

It would already help a lot if the setup.py line says `requests>=2.23.0` instead of `requests==2.23.0`

Thanks in advance for your thoughts!

**Comment by aquatix** [comment]
I noticed you opened a new branch to implement my suggestion (thanks!), but it has spaces around the `>=` - it needs to be written together like in my comment above.

**Comment by themiszamani** [comment]
Upload it to pypi
